version: '3.9'

services:
  elk:
    image: ghcr.io/elk-zone/elk:latest
    container_name: elk
    networks:
      - elk
    env_file:
      - elk.env
    ports:
      - '3000:5314'
    volumes:
      - './elk/data:/elk/data'
    restart: 'always'
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    user: 1000:1000
    networks:
      - gotosocial
    env_file:
      - gotosocial.env
    ports:
      - '80:8080'
    volumes:
      - ./gotosocial/data:/gotosocial/storage
    restart: 'always'

networks:
  elk: 
    driver: bridge
  gotosocial:
    ipam:
      driver: default
