version: "3.9"

services:
  elk: 
    image: ghcr.io/elk-zone/elk:latest
    container_name: elk
    ports: 
      - "3000:5134"
    restart: "always"
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    user: 1000:1000
    networks:
      - gotosocial
    env_file:
      - gotosocial.env
    ports:
      - "80:8080"
    volumes:
      - ./gotosocial/data:/gotosocial/storage
    restart: "always"

networks:
  gotosocial:
    ipam:
      driver: default
